baseURL = "https://plywood.bangunan.co/"
languageCode = "id"
title = "Gudang Triplek | Distributor Triplek, Flywood, Blockbot, Melamin Berbagai Ukuran"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Distributor Triplek berkualitas - Jual Triplek, Plywood, Blockboard, dan Melamin dengan harga bersaing dan gratis biaya pengiriman"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual triplek", "plywood", "blockboard", "melamin", "distributor triplek", "harga triplek", "harga plywood", "triplek murah"]
  base_price = 120000
  price_range = 30000
  free_shipping = true
  materials = [
  "Triplek tebal 3mm",
  "Triplek tebal 6mm",
  "Triplek tebal 9mm",
  "Plywood tebal 12mm",
  "Blockboard tebal 18mm",
  "Melamin tebal 15mm"
  ]
  categories = ["Triplek", "Plywood", "Blockboard", "Melamin"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar Ditempat", "Transfer Setelah Terkirim"]
  area_served = [
    "Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Bandung", "Cimahi", "Sukabumi", "Cirebon", "Garut", "Tasikmalaya", "Sumedang", "Subang", "Karawang", "Purwakarta", "Cianjur", "Majalengka", "Indramayu", "Kuningan", "Banjar", "Pangandaran", "Kabupaten Bandung", "Kabupaten Bogor", "Kabupaten Bekasi", "Kabupaten Cirebon", "Kabupaten Garut", "Kabupaten Indramayu", "Kabupaten Karawang", "Kabupaten Kuningan", "Kabupaten Majalengka", "Kabupaten Pangandaran", "Kabupaten Purwakarta", "Kabupaten Subang", "Kabupaten Sukabumi", "Kabupaten Sumedang", "Kabupaten Tasikmalaya", "Serang", "Cilegon", "Tangerang Selatan", "Lebak", "Pandeglang", "Kabupaten Tangerang", "Kabupaten Serang", "Semarang", "Surakarta", "Magelang", "Salatiga", "Pekalongan", "Tegal", "Cilacap", "Purwokerto", "Pati", "Jepara", "Kudus", "Demak", "Blora", "Grobogan", "Kendal", "Temanggung", "Wonosobo", "Purworejo", "Kabupaten Magelang", "Kabupaten Boyolali", "Kabupaten Klaten", "Kabupaten Sragen", "Kabupaten Karanganyar", "Kabupaten Sukoharjo", "Kabupaten Wonogiri", "Kabupaten Pati", "Kabupaten Blora", "Kabupaten Grobogan", "Kabupaten Kudus", "Kabupaten Jepara", "Kabupaten Demak", "Kabupaten Batang", "Kabupaten Pekalongan", "Kabupaten Pemalang", "Kabupaten Tegal", "Kabupaten Brebes", "Kabupaten Cilacap", "Kabupaten Banyumas", "Kabupaten Purbalingga", "Kabupaten Banjarnegara", "Kabupaten Kebumen", "Kabupaten Temanggung", "Kabupaten Wonosobo", "Kabupaten Kendal", "Kabupaten Semarang", "Kabupaten Purworejo", "Surabaya", "Malang", "Batu", "Blitar", "Kediri", "Mojokerto", "Madiun", "Pasuruan", "Probolinggo", "Jember", "Lumajang", "Bondowoso", "Banyuwangi", "Situbondo", "Ngawi", "Magetan", "Pacitan", "Ponorogo", "Trenggalek", "Tulungagung", "Kabupaten Sidoarjo", "Kabupaten Gresik", "Kabupaten Lamongan", "Kabupaten Bojonegoro", "Kabupaten Tuban", "Kabupaten Jombang", "Kabupaten Nganjuk", "Kabupaten Madiun", "Kabupaten Magetan", "Kabupaten Ngawi", "Kabupaten Pacitan", "Kabupaten Ponorogo", "Kabupaten Blitar", "Kabupaten Tulungagung", "Kabupaten Kediri", "Kabupaten Malang", "Kabupaten Probolinggo", "Kabupaten Pasuruan", "Kabupaten Lumajang", "Kabupaten Jember", "Kabupaten Bondowoso", "Kabupaten Banyuwangi", "Kabupaten Situbondo"
  ]
  return_policies = [
  "Barang bisa ditukar dalam 1 hari jika tidak sesuai.",
  "Barang dapat ditolak jika spesifikasi material tidak sesuai.",
  "Pengembalian gratis untuk barang yang tidak sesuai pesanan."
  ]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Distributor Triplek dan Plywood Berkualitas"
  hero_description = "Kami menawarkan berbagai jenis triplek, plywood, blockboard, dan melamin berkualitas dengan berbagai ukuran. Solusi ideal untuk kebutuhan furniture dan interior Anda, dengan bahan yang kuat dan harga terjangkau."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Triplek & Plywood"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan triplek, plywood, blockboard, dan melamin berkualitas tinggi dengan berbagai ukuran dan harga yang kompetitif. Pengiriman cepat ke seluruh Indonesia, serta konsultasi gratis untuk membantu Anda memilih produk yang tepat untuk proyek Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "plywood.bangunan.co menawarkan berbagai jenis triplek, plywood, blockboard, dan melamin berkualitas dari merk-merk ternama. Kami mengutamakan kepuasan pelanggan dengan produk yang kuat, mudah dipasang, dan harga yang bersaing. Pilih kami untuk memenuhi kebutuhan bahan furniture Anda dengan produk terbaik."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Joko|Andi|Eko|Rudi|Fajar|Hendra|Samsul|Agus|Dedi}"
  message = "{Saya {membeli|memesan|menggunakan} triplek dari plywood.bangunan.co untuk {proyek|pembuatan|bahan} furniture rumah saya, dan hasilnya {sangat memuaskan|memuaskan|luar biasa}. Kualitas produk {sangat baik|premium|terbaik} dan {tahan lama|awet|kuat}.|Triplek dari plywood.bangunan.co {sangat berkualitas|bermutu|kuat} dan {sesuai|ideal|cocok} untuk {proyek|pembuatan} rumah saya.}"
  response = "{Terima kasih atas {kepercayaan|dukungan|pilihan} Anda! Kami senang dapat {menyediakan|menghadirkan|memenuhi} triplek berkualitas untuk {proyek|pembuatan} furniture Anda.|Kami {sangat menghargai|berterima kasih atas} kepercayaan Anda. Senang dapat berkontribusi dalam proyek Anda!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Dewi|Rina|Maya|Lina|Sari|Fitri|Nur|Diah|Ayu}"
  message = "{plywood.bangunan.co {sangat membantu|mempermudah|mengarahkan} dalam memilih triplek untuk rumah saya. Produk yang {saya beli|saya pesan|dikirim} {berkualitas|bermutu|tinggi} dan sesuai dengan kebutuhan saya.|Saya terbantu oleh plywood.bangunan.co dalam memilih produk triplek untuk proyek furniture rumah saya. Produknya {berkualitas|premium|bermutu tinggi} dan sesuai spesifikasi yang dibutuhkan.}"
  response = "{Kami sangat menghargai ulasan Anda. {Senang mendengar|Bahagia mengetahui} bahwa Anda puas dengan triplek dari kami.|Terima kasih atas {ulasan|masukan} Anda! Kami {gembira|senang} Anda puas dengan layanan dan produk kami.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Bambang|Hadi|Tono|Gilang|Bayu|Faisal|Rizal|Ali|Ahmad}"
  message = "{Produk plywood dari plywood.bangunan.co {sangat berkualitas|kuat|bermutu} dan {cocok|sesuai|ideal} untuk proyek furniture {perumahan|rumah} saya. Proses pembelian dan pengirimannya juga {cepat|tepat waktu|efisien}.|Plywood dari plywood.bangunan.co {berkualitas tinggi|premium|kuat} dan {cocok|sesuai|ideal} untuk proyek furniture saya. Pengiriman dan pembeliannya {lancar|tepat waktu|efisien}.}"
  response = "{Terima kasih! Kami {berkomitmen|fokus|dedikasi} untuk menyediakan plywood berkualitas dengan {layanan|pengiriman} terbaik.|Kami {apresiasi|menghargai} ulasan Anda. Terima kasih atas {kepercayaan|pilihan} Anda menggunakan produk kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Bayu|Fajar|Hendra|Dian|Rizky|Yoga|Yudi|Ari|Gani}"
  message = "{Saya {sangat puas|senang|terkesan} dengan plywood dari plywood.bangunan.co. Kualitasnya {sangat baik|luar biasa|berkualitas tinggi} dan {tahan lama|awet|kuat} untuk proyek furniture saya.|Plywood dari plywood.bangunan.co {sangat berkualitas|kuat} dan {tahan lama|awet} untuk proyek furniture yang saya kerjakan.}"
  response = "{Senang mendengar Anda puas dengan {plywood|produk} kami. Terima kasih atas {kepercayaannya|pilihannya|dukungan Anda}!|Kami {bahagia|senang|gembira} Anda puas dengan layanan dan produk kami. Terima kasih atas {kepercayaannya|dukungan Anda}!}"
  rating = 4.9

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Dewi|Lina|Ayu|Fitri|Sari|Diah|Nur|Maya}"
  message = "{Pelayanan plywood.bangunan.co {sangat memuaskan|luar biasa|baik sekali}. Produk triplek yang {saya beli|dikirim} {berkualitas tinggi|bermutu|premium} dan {sesuai dengan harapan|memenuhi ekspektasi|sesuai standar}.|Saya sangat puas dengan {produk|layanan} plywood.bangunan.co. Triplek yang {saya beli|dikirim} {berkualitas tinggi|premium|bermutu} dan {sesuai harapan|memenuhi ekspektasi|sesuai standar}.}"
  response = "{Terima kasih! Kami senang dapat {membantu|mewujudkan|melayani} proyek furniture Anda dengan {produk|triplek} terbaik.|Kami menghargai {ulasan|masukan} Anda. Terima kasih telah {memilih|mempercayai|menggunakan} produk kami!}"
  rating = 4.5

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Agus|Dedi|Toni|Yanto|Wawan|Benny|Rio|Iwan|Galih}"
  message = "{Triplek dari plywood.bangunan.co {sangat sesuai|tepat|cocok} dengan {kebutuhan|spesifikasi|standar} proyek {renovasi|perbaikan} furniture rumah saya. Proses pengirimannya {cepat|tepat waktu|aman} dan {lancar|terorganisir|sesuai jadwal}.|Saya puas dengan {produk|triplek} plywood.bangunan.co untuk proyek furniture rumah saya. Pengirimannya {cepat|tepat waktu|lancar} dan {sesuai harapan|memenuhi ekspektasi|aman}.}"
  response = "{Kami {senang|bahagia|gembira} mendengar bahwa Anda puas dengan {produk|layanan} kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah {mempercayai|memilih|menggunakan} produk kami. Kami {senang|gembira} Anda puas dengan hasilnya.}"
  rating = 5

[[params.tabelItems]]
  name = "Triplek 4mm"
  price = "52.000 /lembar"
[[params.tabelItems]]
  name = "Triplek 6mm"
  price = "82.000 /lembar"
[[params.tabelItems]]
  name = "Triplek 8mm"
  price = "87.000 /lembar"
[[params.tabelItems]]
  name = "Triplek 9mm"
  price = "130.000 /lembar"
[[params.tabelItems]]
  name = "Plywood MDF 18mm"
  price = "180.850 /lembar"
[[params.tabelItems]]
  name = "Plywood Hard Wood 18mm"
  price = "225.850 /lembar"
[[params.tabelItems]]
  name = "Plywood Blockboard 18mm"
  price = "160.850 /lembar"
[[params.tabelItems]]
  name = "Plywood Soft Wood Albasia 18mm"
  price = "167.850 /lembar"
[[params.tabelItems]]
  name = "Melamin 4mm"
  price = "90.000 /lembar"

[params.appliList]
  "Triplek 4mm" = "interior ringan, plafon"
  "Triplek 6mm" = "interior, furniture"
  "Triplek 8mm" = "partisi, furniture"
  "Triplek 9mm" = "furniture berat, partisi"
  "Plywood MDF 18mm" = "papan lantai, partisi"
  "Plywood Hard Wood 18mm" = "furniture berat, lemari"
  "Plywood Blockboard 18mm" = "furniture berat, meja"
  "Plywood Soft Wood Albasia 18mm" = "interior, furniture"
  "Melamin 4mm" = "furniture tahan lama, meja, kabinet"

[params.kegunaanList]
  "Triplek 4mm" = "digunakan untuk plafon dan proyek interior ringan"
  "Triplek 6mm" = "digunakan untuk membuat furniture interior"
  "Triplek 8mm" = "cocok untuk partisi dan furniture"
  "Triplek 9mm" = "cocok untuk furniture berat"
  "Plywood MDF 18mm" = "digunakan untuk papan lantai dan partisi"
  "Plywood Hard Wood 18mm" = "cocok untuk furniture berat dan lemari"
  "Plywood Blockboard 18mm" = "cocok untuk furniture besar dan berat"
  "Plywood Soft Wood Albasia 18mm" = "digunakan untuk furniture interior"
  "Melamin 4mm" = "digunakan untuk furniture tahan lama seperti meja dan kabinet"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Distributor Triplek, Plywood, Blockboard, & Melamin | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"